# Snake AI Introduction Code

In [8]:
import numpy as np
from neural_net import Model
from train import train
import matplotlib.pyplot as plt

In [4]:
# This gets a copy of the neural network we're using, this is just so we can see
# what shape/size the weights vectors are, saving us from manually coding it
model = Model()

In [6]:
# This is the current set of weights
model.get_weights()

[array([[-0.02004123,  0.28701723,  0.272061  ],
        [ 0.7054516 , -0.50572205, -0.79210997],
        [ 0.4091742 , -0.70802116, -0.03580308],
        [ 0.12976038,  0.4797268 , -0.5853251 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[ 0.89239776],
        [ 1.1035613 ],
        [-1.0258186 ]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
# We can see the structure of the network (kind of) with the following
model.model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 4         
Total params: 19
Trainable params: 19
Non-trainable params: 0
_________________________________________________________________


In [9]:
# This just returns vectors the same size as prev_weights filled with random numbers
def random_weights(prev_weights):
    
    # Take the shapes from the original weights vectors
    shapes = [p.shape for p in prev_weights]
    new_weights = []
    
    # Loop over each vector
    for i, s in enumerate(shapes):
        
        # Generate a new vector the same size
        # You can change the distribution [uniform, gaussian, etc] and the
        # range of random numbers (currently [-1, 1])
        new_weights.append(np.random.uniform(-1.0, 1.0, size=s))
        
    return new_weights

In [12]:
# Generate 100 sets of random weights
weights = [random_weights(model.get_weights()) for i in range(100)]

In [13]:
# Now we call the training function with the weights we've generated
# The training function returns the scores that each set of weights achieved
# (press space bar to start the game once the window is open)
generation = 0
score = train(generation, weights)